version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - unparam
    - gocritic

  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - commentFormatting
        - hugeParam
    unparam:
      check-exported: false

  exclusions:
    paths:
      - dist
    rules:
      - linters:
          - lll
        source: "^//go:generate "
    max-issues-per-linter: 50
    max-same-issues: 5
